[package]
name = "rcli"
authors = ["dazhao <zhaihaibo98@@126.com>"]
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
clap = { version = "4.5.23", features = ["derive"] }
csv = "1.3.1"
serde = { version = "1.0.216", features = ["derive"] }
serde_json = "1.0.134"
 